name: onboarding2
favicon: null
layout_spectrum: 0.00751458783634007
typography_spectrum: 0.30233286833390594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.33909246418625116
  lightness: 0.10795332957059145
  saturation: 0.49448804510757327
  rhythmicContrast: 0.5958562912419438
purpose: []
